<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.3" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.3" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.1.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\services\gateway\ApiGateway\ApiGateway.csproj" />
    <ProjectReference Include="..\services\user-management\UserManagement\UserManagement.csproj" />
    <ProjectReference Include="..\services\inventory\InventoryManagement\InventoryManagement.csproj" />
    <ProjectReference Include="..\services\sales\SalesManagement\SalesManagement.csproj" />
    <ProjectReference Include="..\services\financial\FinancialManagement\FinancialManagement.csproj" />
    <ProjectReference Include="..\services\dashboard\DashboardAnalytics\DashboardAnalytics.csproj" />
  </ItemGroup>

</Project>
