apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp-local

resources:
  - namespace.yaml  # Local environment namespace
  - ../base         # Reference the entire base directory

patches:
  - path: user-management-resources.yaml
    target:
      kind: Deployment
      name: user-management
  - path: prometheus-resources.yaml
    target:
      kind: Deployment
      name: prometheus

